getting a button working onclick not working
serge-web/serge pull request #130
Opened 2020-01-11 10:05 UTC by lm93547

## 🧰 Ticket
[The ticket the work was done for as a ticket reference (e.g. `closes #1`)]

## 🚀 Overview: 
[A summary of what you did in no more than one paragraph]

## 🔗 Link to preview
[If you're on a project which auto-deploys branches, link to the branches preview link here]

## 🤔 Reason: 
[Why did you do what you did? - feel free to copy from the ticket if the reason is there]

## 🔨Work carried out:

I have added a new button, but only one of the on clicks is working

- [x] Tests pass

## 🖥️ Screenshot
[If the work is UI related then paste a screenshot of the update here.]

## 📝 Developer Notes:
[Sometimes, extra notes are needed to add clarity to a PR, add them here]

2020-01-12 08:35 UTC, IanMayo requested changes
Thanks for the update.  

A couple of fixes please:

1. On Chrome/Macos the control doesn't match the existing ones:
![image](https://user-images.githubusercontent.com/1108513/72216214-44ea9b80-3516-11ea-9a77-f87434d4976c.png)

2. Again on Chrome/Macos the map zooms out too far.  The map should _Fill_ the viewport, not have large borders:
![image](https://user-images.githubusercontent.com/1108513/72216234-76636700-3516-11ea-9026-ee72d87ffc2f.png)

2020-01-12 13:20 UTC, IanMayo requested changes
Not great.

1. Setting the zoom level does't scale the plot to the viewport. With a shallow browser window, not all of the map is displayed:
![image](https://user-images.githubusercontent.com/1108513/72219390-86db0800-353d-11ea-9cf6-4ba47d56d919.png)

2. Please don't leave `console.log()` statements in there.  It's quite right to use them during development, but they should be removed when you're happy with the code.
3. Code outside your own module should only be modified with good reason.  Did you need to modify `zoomSnap` and `zoomDelta` ?

2020-01-13 09:07 UTC, IanMayo commented on packages/client/src/Helpers/zoomHome.js
> +        // using set timeout which fitsBounds on maximise click (needs a delay as the CSS transition is not finished)
@lm93547  - could you teach me about the delay this CSS transition?

What is the problem we have to overcome? Can you give me a link to where I can learn more?

2020-01-13 09:39 UTC, IanMayo commented
![Hover action](https://i.gyazo.com/6bdb2c37be2fac3c37212acc8653b40d.gif)

On my system the Leaflet hover highlighting is for the background to go grey, but it goes pink for the home button.

Maybe the leaflet controls go pink your operating system.

Is it an option to find (via 'inspect' the CSS class (or color) name) for the existing zoom in/out buttons, and copy that for the home button?

2020-01-13 17:06 UTC, IanMayo commented
Closing #140 resolves a number of issues in this version.

2020-01-13 17:06 UTC, closed without merging

2020-01-13 22:49 UTC, lm93547 commented
Hi Ian. The reason the hover goes pink is the zoomHome.js has a hover event set to pink, this was purely to test if the hover was working.