Can not see full map of CoreMapping when maximize screen after divide channel to multi side
serge-web/serge pull request #2883
Opened 2024-02-21 15:14 UTC by lebaphi

Fixes #2857

2024-02-22 07:35 UTC, Tristina1788 commented
@IanMayo @lebaphi   Tested on '2857-disable-maximize' branch. Now 'maximize' button is not showed  for all channels. But user want to see full map after divide channel to multi side, so he have to drag the core mapping channel to full screen. With this way, it makes user confuse because he doesn't see another channel on screen. 


https://github.com/serge-web/serge/assets/107697044/251f94dd-edd9-4dc0-8108-c97d142aeec3

2024-02-22 10:31 UTC, IanMayo commented
> it makes user confuse because he doesn't see another channel on screen

Thanks @Tristina1788 - could you create that as another issue please?

2024-02-22 13:33 UTC, Tristina1788 submitted a review, later dismissed
I created #2886 . This ticket is fixing for disable 'Maximize' Button and it works fine. Approved.

2024-02-22 13:57 UTC, IanMayo requested changes
Hello @lebaphi - this is a valid solution, but....

Could you do a quick investigation of removing `maximise` by configuring the panel layout?   I suspect that may give us a more robust solution.
![image](https://github.com/serge-web/serge/assets/1108513/02cf5c3f-927c-4da3-864a-2a0bda9db44e)

2024-02-25 04:32 UTC, lebaphi commented
I've updated the solution as your suggestion @IanMayo

2024-02-26 02:21 UTC, Tristina1788 commented
@lebaphi , @IanMayo  Tested on '2857-disable-maximize' , now the issue is happened with the latest code

https://github.com/serge-web/serge/assets/107697044/aa1f2309-dd43-45d1-8bc0-078da88f7ef1

2024-02-26 10:08 UTC, IanMayo commented
@Tristina1788 - after I cleared the cache for the browser tab running the game, the maximise button disappaered:
![image](https://github.com/serge-web/serge/assets/1108513/76d09270-c9f5-4aac-9543-85fc043285fd)

2024-02-26 10:09 UTC, IanMayo approved these changes
Now there's a nice neat fix @lebaphi :-D

2024-02-26 10:09 UTC, merged

2024-02-26 11:19 UTC, Tristina1788 commented
> @Tristina1788 - after I cleared the cache for the browser tab running the game, the maximise button disappaered: ![image](https://private-user-images.githubusercontent.com/1108513/307746160-76d09270-c9f5-4aac-9543-85fc043285fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDU4NjEsIm5iZiI6MTcwODk0NTU2MSwicGF0aCI6Ii8xMTA4NTEzLzMwNzc0NjE2MC03NmQwOTI3MC1jOWY1LTRhYWMtOTU0My04NWZjMDQzMjg1ZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMTEwNjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTcwZmFhMTQ0NmU2NGM5NGM2MGE5NzMzYmE5YWU2OTE0YzZmOTk0Zjc2NmJlMTdjMTkzNDljNDYyNzdiMjE2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CE3wSE3NEpm6t9dye8ZN0xLiqz7pOCgJ4eFDHbex348)

I get issue whey try to open map with bigger size after divie channel to multi side (I clear cache before) . @IanMayo How do you think? should we fix it? I remember the before fixing didn't get this issue.

https://github.com/serge-web/serge/assets/107697044/37fce2e2-3b8f-4f92-8d34-18b1754fc729

2024-02-26 11:21 UTC, IanMayo commented
Yes, that's a new issue, please @Tristina1788 . I guess the issue is "map tiles not downloaded when map area expanded"