Bugfix/578 snapshot generation
serge-web/serge pull request #672
Opened 2021-04-15 10:47 UTC by sandro768

## 🧰 Issue

## 🚀 Overview: 

## 🔗 Link to preview

## 🤔 Reason: 

## 🔨Work carried out:

- [x] Tests pass

## 🖥️ Screenshot

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

## 📝 Developer Notes:

2021-04-15 14:02 UTC, IanMayo commented on packages/components/__mocks__/@fortawesome/react-fontawesome.tsx
> + * Mocks @fortawesome/react-fontawesome.js to return a simple, empty <svg> element
hey - well spotted!

2021-04-15 14:32 UTC, IanMayo requested changes
Thanks, nice work.

Note: when I run jest coverage I get snapshot errors like this:
![image](https://user-images.githubusercontent.com/1108513/114886236-48e32880-9dff-11eb-853b-b8b8d8b07781.png)

I think it's clear what's happening there.  The `dateTime` value is 15:08...Z.  The `Z` means it's UTC.  But, moment is switching it to your timezone, which is `19:08`.

I think that for our tests, we need to tell moment to always use UTC - then whereever the developer is, the times will be formatted the same.

It looks like we can tell moment what timezone to use:
https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/

So, we _probably_ just need to set that default in each `.spec` that needs it.

Hmm, how can you find where it's needed.  You could change your timezone and re-run your tests, then ones with time would fail.

Or, I can update the snapshots so they're all UTC - then when you run your tests they will fail until the default timezones are set.

2021-04-16 13:18 UTC, IanMayo commented
Hello @sandro768  - do you think you'll have chance to make the above timezone-related fix?

2021-04-16 13:20 UTC, sandro768 commented
> Hello @sandro768 - do you think you'll have chance to make the above timezone-related fix?

I think the one way of doing is to mock the data the same way it's done for font-awesome icons.

2021-04-16 13:24 UTC, IanMayo commented
You don't think the fix to set the local timezone to UTC in all instances won't fix it?

2021-04-16 13:26 UTC, sandro768 commented
> You don't think the fix to set the local timezone to UTC in all instances won't fix it?

Do we want to fix the local timezone in the components or tests only?

2021-04-16 13:28 UTC, IanMayo commented
It would only have to happen in the tests.  If we did it in the deployed app then daylight-savings-time won't be respected.

2021-04-16 18:30 UTC, sandro768 commented
@IanMayo It's ready for testing

2021-04-17 13:58 UTC, IanMayo approved these changes

2021-04-17 13:58 UTC, merged