Collapse on message submit
serge-web/serge pull request #919
Opened 2021-07-02 11:59 UTC by sanjayradadiya

## 🧰 Issue

Fixes #898 

## 🚀 Overview: 

## 🔗 Link to preview

## 🤔 Reason: 

## 🔨Work carried out:

- [x] Tests pass

## 🖥️ Screenshot

![Kapture 2021-07-02 at 17 24 27](https://user-images.githubusercontent.com/16476120/124271384-0659fe00-db5b-11eb-9932-1ae548610574.gif)

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

## 📝 Developer Notes:

2021-07-02 16:04 UTC, IanMayo requested changes
Thanks @sanjayradadiya - working fine.

Could you sort the static analysis issues please?

2021-07-02 16:10 UTC, sanjayradadiya commented
> Thanks @sanjayradadiya - working fine.
> 
> Could you sort the static analysis issues please?

Sorry, what's need to be fixed here ?

2021-07-02 16:23 UTC, IanMayo commented
> static analysis is not showing any proper issues

I see this:
![image](https://user-images.githubusercontent.com/1108513/124303278-2806b580-db5a-11eb-9379-77e4233b8827.png)

2021-07-05 12:02 UTC, IanMayo approved these changes

2021-07-05 12:02 UTC, merged